=== binaryage/dirac/scripts/json_validator/module.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "extensions": {
      "type": "array",
      "description": "Extension points",
      "items": {
        "properties": {
          "type": {"type": "string"},
          "order": {"type": "number"}
        }
      }
    },
    "dependencies": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "scripts": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "modules": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "resources": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "skip_compilation": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "experiment": {
      "type": "string"
    }
  },
  "definitions": {
  }
}

=== binaryage/dirac/front_end/web_audio/module.json
{
  "extensions": [
      {
          "type": "view",
          "location": "drawer-view",
          "id": "web-audio",
          "title": "WebAudio",
          "persistence": "closeable",
          "order": 100,
          "className": "WebAudio.WebAudioView",
          "tags": "audio"
      }
  ],
  "dependencies": [
      "components",
      "sdk",
      "ui"
  ],
  "scripts": [
      "graph_visualizer/Types.js",
      "graph_visualizer/GraphStyle.js",
      "graph_visualizer/GraphManager.js",
      "graph_visualizer/NodeRendererUtility.js",
      "graph_visualizer/NodeView.js",
      "graph_visualizer/EdgeView.js",
      "graph_visualizer/GraphView.js",
      "WebAudioModel.js",
      "AudioContextSelector.js",
      "AudioContextContentBuilder.js",
      "WebAudioView.js"
  ],
  "resources": [
      "webAudio.css",
      "audioContextSelector.css"
  ]
}

=== binaryage/dirac/resources/unpacked/devtools/front_end/emulation/module.json
{
  "extensions": [
    {
      "type": "@Common.AppProvider",
      "condition": "can_dock",
      "className": "Emulation.AdvancedAppProvider",
      "order": 0
    },
    {
      "type": "action",
      "category": "Mobile",
      "actionId": "emulation.toggle-device-mode",
      "toggleable": true,
      "className": "Emulation.DeviceModeWrapper.ActionDelegate",
      "condition": "can_dock",
      "title": "Toggle device toolbar",
      "iconClass": "largeicon-phone",
      "bindings": [
        {
          "platform": "windows,linux",
          "shortcut": "Shift+Ctrl+M"
        },
        {
          "platform": "mac",
          "shortcut": "Shift+Meta+M"
        }
      ]
    },
    {
      "type": "action",
      "actionId": "emulation.capture-screenshot",
      "category": "Screenshot",
      "className": "Emulation.DeviceModeWrapper.ActionDelegate",
      "title": "Capture screenshot"
    },
    {
      "type": "context-menu-item",
      "location": "deviceModeMenu/save",
      "order": 12,
      "actionId": "emulation.capture-screenshot"
    },
    {
      "type": "@UI.ToolbarItem.Provider",
      "actionId": "emulation.toggle-device-mode",
      "condition": "can_dock",
      "location": "main-toolbar-left",
      "order": 1
    },
    {
      "type": "action",
      "actionId": "emulation.capture-full-height-screenshot",
      "category": "Screenshot",
      "className": "Emulation.DeviceModeWrapper.ActionDelegate",
      "title": "Capture full size screenshot"
    },
    {
      "type": "action",
      "actionId": "emulation.capture-node-screenshot",
      "category": "Screenshot",
      "className": "Emulation.DeviceModeWrapper.ActionDelegate",
      "title": "Capture node screenshot"
    },
    {
      "type": "context-menu-item",
      "location": "deviceModeMenu/save",
      "order": 13,
      "actionId": "emulation.capture-full-height-screenshot"
    },
    {
      "type": "setting",
      "category": "Mobile",
      "settingName": "showMediaQueryInspector",
      "settingType": "boolean",
      "defaultValue": false,
      "options": [
        {
          "value": true,
          "title": "Show media queries"
        },
        {
          "value": false,
          "title": "Hide media queries"
        }
      ],
      "tags": "device"
    },
    {
      "type": "setting",
      "category": "Mobile",
      "settingName": "emulation.showRulers",
      "settingType": "boolean",
      "defaultValue": false,
      "options": [
        {
          "value": true,
          "title": "Show rulers"
        },
        {
          "value": false,
          "title": "Hide rulers"
        }
      ],
      "tags": "device"
    },
    {
      "type": "setting",
      "category": "Mobile",
      "settingName": "emulation.showDeviceOutline",
      "settingType": "boolean",
      "defaultValue": false,
      "options": [
        {
          "value": true,
          "title": "Show device frame"
        },
        {
          "value": false,
          "title": "Hide device frame"
        }
      ],
      "tags": "device"
    },
    {
      "type": "view",
      "location": "settings-view",
      "id": "devices",
      "title": "Devices",
      "order": 30,
      "className": "Emulation.DevicesSettingsTab",
      "settings": [
        "standardEmulatedDeviceList",
        "customEmulatedDeviceList"
      ]
    },
    {
      "type": "action",
      "actionId": "emulation.show-sensors",
      "category": "Sensors",
      "title": "Sensors",
      "className": "Emulation.SensorsView.ShowActionDelegate"
    },
    {
      "type": "view",
      "location": "drawer-view",
      "id": "sensors",
      "title": "Sensors",
      "persistence": "closeable",
      "order": 100,
      "className": "Emulation.SensorsView",
      "tags": "geolocation, timezones, locale, locales, accelerometer, device orientation"
    },
    {
      "type": "setting",
      "settingName": "emulation.locations",
      "settingType": "array",
      "defaultValue": [
        {
          "title": "Berlin",
          "lat": 52.520007,
          "long": 13.404954,
          "timezoneId": "Europe/Berlin",
          "locale": "de_DE"
        },
        {
          "title": "London",
          "lat": 51.507351,
          "long": -0.127758,
          "timezoneId": "Europe/London",
          "locale": "en_GB"
        },
        {
          "title": "Moscow",
          "lat": 55.755826,
          "long": 37.6173,
          "timezoneId": "Europe/Moscow",
          "locale": "ru_RU"
        },
        {
          "title": "Mountain View",
          "lat": 37.386052,
          "long": -122.083851,
          "timezoneId": "US/Pacific",
          "locale": "en_US"
        },
        {
          "title": "Mumbai",
          "lat": 19.075984,
          "long": 72.877656,
          "timezoneId": "Asia/Kolkata",
          "locale": "mr_IN"
        },
        {
          "title": "San Francisco",
          "lat": 37.774929,
          "long": -122.419416,
          "timezoneId": "US/Pacific",
          "locale": "en_US"
        },
        {
          "title": "Shanghai",
          "lat": 31.230416,
          "long": 121.473701,
          "timezoneId": "Asia/Shanghai",
          "locale": "zh_Hans_CN"
        },
        {
          "title": "SÃ£o Paulo",
          "lat": -23.55052,
          "long": -46.633309,
          "timezoneId": "America/Sao_Paulo",
          "locale": "pt_BR"
        },
        {
          "title": "Tokyo",
          "lat": 35.689487,
          "long": 139.691706,
          "timezoneId": "Asia/Tokyo",
          "locale": "ja_JP"
        }
      ]
    },
    {
      "type": "view",
      "location": "settings-view",
      "id": "emulation-locations",
      "title": "Locations",
      "order": 40,
      "className": "Emulation.LocationsSettingsTab",
      "settings": [
        "emulation.locations"
      ]
    }
  ],
  "dependencies": [
    "bindings",
    "components",
    "platform",
    "ui",
    "mobile_throttling"
  ],
  "scripts": [],
  "modules": [
    "emulation.js",
    "emulation-legacy.js",
    "AdvancedApp.js",
    "DeviceModeModel.js",
    "DeviceModeToolbar.js",
    "DeviceModeView.js",
    "DeviceModeWrapper.js",
    "DevicesSettingsTab.js",
    "EmulatedDevices.js",
    "InspectedPagePlaceholder.js",
    "LocationsSettingsTab.js",
    "MediaQueryInspector.js",
    "SensorsView.js"
  ],
  "resources": [
    "deviceModeToolbar.css",
    "deviceModeView.css",
    "devicesSettingsTab.css",
    "inspectedPagePlaceholder.css",
    "locationsSettingsTab.css",
    "mediaQueryInspector.css",
    "sensors.css"
  ]
}

=== binaryage/dirac/front_end/layer_viewer/module.json
{
    "dependencies": [
        "components",
        "sdk",
        "timeline_model",
        "ui",
        "perf_ui"
    ],
    "scripts": [],
    "modules": [
        "LayerDetailsView.js",
        "LayerTreeOutline.js",
        "LayerViewHost.js",
        "Layers3DView.js",
        "PaintProfilerView.js",
        "TransformController.js"
    ],
    "resources": [
        "layers3DView.css",
        "paintProfiler.css",
        "layerDetailsView.css"
    ]
}

=== binaryage/dirac/resources/unpacked/devtools/front_end/perf_ui/module.json
{
    "extensions": [
        {
            "type": "late-initialization",
            "className": "PerfUI.LiveHeapProfile",
            "experiment": "liveHeapProfile"
        },
        {
            "type": "@SourceFrame.LineDecorator",
            "className": "PerfUI.LineLevelProfile.LineDecorator",
            "decoratorType": "performance"
        },
        {
            "type": "@SourceFrame.LineDecorator",
            "className": "PerfUI.LineLevelProfile.LineDecorator",
            "decoratorType": "memory"
        },
        {
            "type": "setting",
            "category": "Performance",
            "title": "Flamechart mouse wheel action:",
            "settingName": "flamechartMouseWheelAction",
            "settingType": "enum",
            "defaultValue": "zoom",
            "options": [
                {
                    "title": "Scroll",
                    "text": "Scroll",
                    "value": "scroll"
                },
                {
                    "title": "Zoom",
                    "text": "Zoom",
                    "value": "zoom"
                }
            ]
        },
        {
            "type": "action",
            "actionId": "components.collect-garbage",
            "title": "Collect garbage",
            "iconClass": "largeicon-trash-bin",
            "className": "PerfUI.GCActionDelegate"
        }
    ],
    "dependencies": [
        "ui",
        "sdk",
        "bindings",
        "source_frame",
        "text_editor"
    ],
    "scripts": [
        "ChartViewport.js",
        "FilmStripView.js",
        "FlameChart.js",
        "GCActionDelegate.js",
        "LineLevelProfile.js",
        "LiveHeapProfile.js",
        "NetworkPriorities.js",
        "OverviewGrid.js",
        "PieChart.js",
        "TimelineGrid.js",
        "TimelineOverviewPane.js"
    ],
    "resources": [
        "chartViewport.css",
        "filmStripView.css",
        "flameChart.css",
        "overviewGrid.css",
        "pieChart.css",
        "timelineGrid.css",
        "timelineOverviewInfo.css"
    ]
}

=== binaryage/dirac/front_end/coverage/module.json
{
  "extensions": [
    {
      "type": "view",
      "location": "drawer-view",
      "id": "coverage",
      "title": "Coverage",
      "persistence": "closeable",
      "className": "Coverage.CoverageView",
      "order": 100
    },
    {
      "type": "@SourceFrame.LineDecorator",
      "className": "Coverage.CoverageView.LineDecorator",
      "decoratorType": "coverage"
    },
    {
      "type": "action",
      "actionId": "coverage.toggle-recording",
      "iconClass": "largeicon-start-recording",
      "toggleable": true,
      "toggledIconClass": "largeicon-stop-recording",
      "toggleWithRedColor": true,
      "className": "Coverage.CoverageView.ActionDelegate",
      "category": "Performance",
      "options": [
        {
          "value": true,
          "title": "Instrument coverage"
        },
        {
          "value": false,
          "title": "Stop instrumenting coverage and show results"
        }
      ]
    },
    {
      "type": "action",
      "actionId": "coverage.start-with-reload",
      "iconClass": "largeicon-refresh",
      "className": "Coverage.CoverageView.ActionDelegate",
      "category": "Performance",
      "title": "Start instrumenting coverage and reload page"
    }
  ],
  "dependencies": [
    "bindings",
    "common",
    "data_grid",
    "formatter",
    "host",
    "platform",
    "sdk",
    "source_frame",
    "text_utils",
    "ui",
    "workspace"
  ],
  "modules": [
    "coverage.js",
    "coverage-legacy.js",
    "CoverageModel.js",
    "CoverageListView.js",
    "CoverageView.js",
    "CoverageDecorationManager.js"
  ],
  "resources": [
    "coverageListView.css",
    "coverageView.css"
  ]
}

=== binaryage/dirac/front_end/emulation/module.json
{
    "extensions": [
        {
            "type": "@Common.AppProvider",
            "condition": "can_dock",
            "className": "Emulation.AdvancedAppProvider",
            "order": 0
        },
        {
            "type": "action",
            "category": "Mobile",
            "actionId": "emulation.toggle-device-mode",
            "className": "Emulation.DeviceModeWrapper.ActionDelegate",
            "condition": "can_dock",
            "title": "Toggle device toolbar",
            "iconClass": "largeicon-phone",
            "bindings": [
                {
                    "platform": "windows,linux",
                    "shortcut": "Shift+Ctrl+M"
                },
                {
                    "platform": "mac",
                    "shortcut": "Shift+Meta+M"
                }
            ]
        },
        {
            "type": "action",
            "actionId": "emulation.capture-screenshot",
            "category": "Mobile",
            "className": "Emulation.DeviceModeWrapper.ActionDelegate",
            "title": "Capture screenshot",
            "tags": "device"
        },
        {
            "type": "context-menu-item",
            "location": "deviceModeMenu/save",
            "order": 12,
            "actionId": "emulation.capture-screenshot"
        },
        {
            "type": "@UI.ToolbarItem.Provider",
            "actionId": "emulation.toggle-device-mode",
            "condition": "can_dock",
            "location": "main-toolbar-left",
            "order": 1
        },
        {
            "type": "action",
            "actionId": "emulation.capture-full-height-screenshot",
            "category": "Mobile",
            "className": "Emulation.DeviceModeWrapper.ActionDelegate",
            "title": "Capture full size screenshot",
            "tags": "device"
        },
        {
            "type": "action",
            "actionId": "emulation.capture-node-screenshot",
            "category": "Mobile",
            "className": "Emulation.DeviceModeWrapper.ActionDelegate",
            "title": "Capture node screenshot",
            "tags": "device"
        },
        {
            "type": "context-menu-item",
            "location": "deviceModeMenu/save",
            "order": 13,
            "actionId": "emulation.capture-full-height-screenshot"
        },
        {
            "type": "setting",
            "category": "Mobile",
            "settingName": "showMediaQueryInspector",
            "settingType": "boolean",
            "defaultValue": false,
            "options": [
                {
                    "value": true,
                    "title": "Show media queries"
                },
                {
                    "value": false,
                    "title": "Hide media queries"
                }
            ],
            "tags": "device"
        },
        {
            "type": "setting",
            "category": "Mobile",
            "settingName": "emulation.showRulers",
            "settingType": "boolean",
            "defaultValue": false,
            "options": [
                {
                    "value": true,
                    "title": "Show rulers"
                },
                {
                    "value": false,
                    "title": "Hide rulers"
                }
            ],
            "tags": "device"
        },
        {
            "type": "setting",
            "category": "Mobile",
            "settingName": "emulation.showDeviceOutline",
            "settingType": "boolean",
            "defaultValue": false,
            "options": [
                {
                    "value": true,
                    "title": "Show device frame"
                },
                {
                    "value": false,
                    "title": "Hide device frame"
                }
            ],
            "tags": "device"
        },
        {
            "type": "view",
            "location": "settings-view",
            "id": "devices",
            "title": "Devices",
            "order": 30,
            "className": "Emulation.DevicesSettingsTab",
            "settings": [
                "standardEmulatedDeviceList",
                "customEmulatedDeviceList"
            ]
        },
        {
            "type": "action",
            "actionId": "emulation.show-sensors",
            "title": "Sensors",
            "className": "Emulation.SensorsView.ShowActionDelegate"
        },
        {
            "type": "view",
            "location": "drawer-view",
            "id": "sensors",
            "title": "Sensors",
            "persistence": "closeable",
            "order": 100,
            "className": "Emulation.SensorsView",
            "tags": "geolocation, accelerometer, device orientation"
        }
    ],
    "dependencies": [
        "bindings",
        "components",
        "platform",
        "ui",
        "mobile_throttling"
    ],
    "scripts": [
        "AdvancedApp.js",
        "EmulatedDevices.js",
        "DevicesSettingsTab.js",
        "InspectedPagePlaceholder.js",
        "MediaQueryInspector.js",
        "SensorsView.js",
        "DeviceModeModel.js",
        "DeviceModeToolbar.js",
        "DeviceModeView.js",
        "DeviceModeWrapper.js"
    ],
    "resources": [
        "devicesSettingsTab.css",
        "deviceModeToolbar.css",
        "deviceModeView.css",
        "inspectedPagePlaceholder.css",
        "mediaQueryInspector.css",
        "sensors.css"
    ]
}

=== binaryage/dirac/resources/unpacked/devtools/front_end/inspector_main/module.json
{
  "extensions": [
    {
      "type": "early-initialization",
      "className": "InspectorMain.InspectorMain"
    },
    {
      "type": "action",
      "category": "Navigation",
      "actionId": "inspector_main.reload",
      "className": "InspectorMain.ReloadActionDelegate",
      "iconClass": "largeicon-refresh",
      "title": "Reload page",
      "bindings": [
        {
          "platform": "windows,linux",
          "shortcut": "Ctrl+R"
        },
        {
          "platform": "windows,linux",
          "shortcut": "F5"
        },
        {
          "platform": "mac",
          "shortcut": "Meta+R"
        }
      ]
    },
    {
      "type": "action",
      "category": "Navigation",
      "actionId": "inspector_main.hard-reload",
      "className": "InspectorMain.ReloadActionDelegate",
      "title": "Hard reload page",
      "bindings": [
        {
          "platform": "windows,linux",
          "shortcut": "Shift+Ctrl+R"
        },
        {
          "platform": "windows,linux",
          "shortcut": "Shift+F5"
        },
        {
          "platform": "windows,linux",
          "shortcut": "Ctrl+F5"
        },
        {
          "platform": "windows,linux",
          "shortcut": "Ctrl+Shift+F5"
        },
        {
          "platform": "mac",
          "shortcut": "Shift+Meta+R"
        }
      ]
    },
    {
      "type": "@UI.ToolbarItem.Provider",
      "className": "InspectorMain.NodeIndicator",
      "order": 2,
      "location": "main-toolbar-left"
    },
    {
      "type": "setting",
      "category": "Network",
      "title": "Force ad blocking on this site",
      "settingName": "network.adBlockingEnabled",
      "settingType": "boolean",
      "storageType": "session",
      "defaultValue": false,
      "options": [
        {
          "value": true,
          "title": "Block ads on this site"
        },
        {
          "value": false,
          "title": "Show ads on this site, if allowed"
        }
      ]
    },
    {
      "type": "setting",
      "category": "Global",
      "title": "Auto-open DevTools for popups",
      "settingName": "autoAttachToCreatedPages",
      "settingType": "boolean",
      "order": 2,
      "defaultValue": false,
      "options": [
        {
          "value": true,
          "title": "Auto-open DevTools for popups"
        },
        {
          "value": false,
          "title": "Do not auto-open DevTools for popups"
        }
      ]
    },
    {
      "type": "setting",
      "category": "Global",
      "title": "Emulate a focused page",
      "settingName": "emulatePageFocus",
      "settingType": "boolean",
      "storageType": "session",
      "order": 2,
      "defaultValue": false,
      "options": [
        {
          "value": true,
          "title": "Emulate a focused page"
        },
        {
          "value": false,
          "title": "Do not emulate a focused page"
        }
      ]
    },
    {
      "type": "setting",
      "category": "Appearance",
      "title": "Don't show Chrome Data Saver warning",
      "settingName": "disableDataSaverInfobar",
      "settingType": "boolean",
      "defaultValue": false
    },
    {
      "type": "setting",
      "category": "Appearance",
      "title": "Disable paused state overlay",
      "settingName": "disablePausedStateOverlay",
      "settingType": "boolean",
      "defaultValue": false
    },
    {
      "type": "view",
      "location": "drawer-view",
      "id": "rendering",
      "title": "Rendering",
      "persistence": "closeable",
      "order": 50,
      "className": "InspectorMain.RenderingOptionsView",
      "tags": "paint, layout, fps, CSS media type, CSS media feature, vision deficiency, color vision deficiency"
    }
  ],
  "dependencies": [
    "components",
    "mobile_throttling"
  ],
  "scripts": [],
  "modules": [
    "inspector_main.js",
    "inspector_main-legacy.js",
    "RenderingOptions.js",
    "InspectorMain.js"
  ],
  "resources": [
    "nodeIcon.css",
    "renderingOptions.css"
  ]
}

=== binaryage/dirac/resources/unpacked/devtools/front_end/text_editor/module.json
{
  "extensions": [
    {
      "type": "@TextUtils.TokenizerFactory",
      "className": "TextEditor.CodeMirrorUtils.TokenizerFactory"
    },
    {
      "type": "@UI.TextEditorFactory",
      "className": "TextEditor.CodeMirrorTextEditorFactory"
    }
  ],
  "dependencies": [
    "ui",
    "platform",
    "common",
    "cm",
    "cm_web_modes"
  ],
  "scripts": [],
  "modules": [
    "text_editor.js",
    "text_editor-legacy.js",
    "CodeMirrorUtils.js",
    "TextEditorAutocompleteController.js",
    "CodeMirrorTextEditor.js"
  ],
  "resources": [
    "autocompleteTooltip.css",
    "cmdevtools.css"
  ]
}
