=== binaryage/dirac/scripts/json_validator/module.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "extensions": {
      "type": "array",
      "description": "Extension points",
      "items": {
        "properties": {
          "type": {"type": "string"},
          "order": {"type": "number"}
        }
      }
    },
    "dependencies": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "scripts": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "modules": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "resources": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "skip_compilation": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "experiment": {
      "type": "string"
    }
  },
  "definitions": {
  }
}

=== binaryage/dirac/resources/unpacked/devtools/front_end/media/module.json
{
  "extensions": [
      {
          "type": "view",
          "location": "panel",
          "id": "media",
          "title": "Media",
          "persistence": "closeable",
          "order": 100,
          "className": "Media.MainView",
          "tags": "media, video",
          "experiment": "mediaInspector"
      }
  ],
  "dependencies": [
      "components",
      "sdk",
      "ui",
      "data_grid",
      "source_frame"
  ],
  "scripts": [
      "EventDisplayTable.js",
      "MainView.js",
      "PlayerDetailView.js",
      "PlayerListView.js",
      "PlayerPropertiesView.js",
      "MediaModel.js",
      "ChevronTabbedPanel.js"
  ],
  "resources": [
    "eventDisplayTable.css",
    "mediaView.css",
    "playerListView.css",
    "playerPropertiesView.css",
    "chevronTabbedPanel.css"
  ]
}

=== binaryage/dirac/front_end/developer_resources/module.json
{
  "extensions": [
    {
      "type": "view",
      "location": "drawer-view",
      "id": "resource-loading-pane",
      "title": "Developer Resources",
      "order": 100,
      "persistence": "closeable",
      "className": "DeveloperResources.DeveloperResourcesView",
      "experiment": "developerResourcesView"
    }
  ],  "dependencies": [
    "common",
    "platform",
    "ui",
    "host",
    "components",
    "sdk",
    "network",
    "browser_sdk"
  ],
  "modules": [
    "developer_resources.js",
    "developer_resources-legacy.js",
    "DeveloperResourcesView.js",
    "DeveloperResourcesListView.js"
  ],
  "resources": [
    "developerResourcesView.css",
    "developerResourcesListView.css"
  ]
}

=== binaryage/dirac/resources/unpacked/devtools/front_end/quick_open/module.json
{
  "extensions": [
    {
      "type": "@QuickOpen.FilteredListWidget.Provider",
      "title": "Run command",
      "prefix": ">",
      "className": "QuickOpen.CommandMenuProvider"
    },
    {
      "type": "@QuickOpen.FilteredListWidget.Provider",
      "prefix": "?",
      "className": "QuickOpen.HelpQuickOpen"
    },
    {
      "type": "action",
      "actionId": "commandMenu.show",
      "category": "Global",
      "title": "Run command",
      "className": "QuickOpen.CommandMenu.ShowActionDelegate",
      "bindings": [
        {
          "platform": "windows,linux",
          "shortcut": "Ctrl+Shift+P",
          "keybindSets": ["devToolsDefault", "vsCode"]
        },
        {
          "platform": "mac",
          "shortcut": "Meta+Shift+P",
          "keybindSets": ["devToolsDefault", "vsCode"]
        },
        {
          "shortcut": "F1",
          "keybindSets": ["vsCode"]
        }
      ]
    },
    {
      "type": "context-menu-item",
      "location": "mainMenu/default",
      "actionId": "commandMenu.show"
    },
    {
      "type": "action",
      "actionId": "quickOpen.show",
      "category": "Global",
      "title": "Open file",
      "className": "QuickOpen.QuickOpen.ShowActionDelegate",
      "order": 100,
      "bindings": [
        {
          "platform": "mac",
          "shortcut": "Meta+P",
          "keybindSets": ["devToolsDefault", "vsCode"]
        },
        {
          "platform": "mac",
          "shortcut": "Meta+O",
          "keybindSets": ["devToolsDefault", "vsCode"]
        },
        {
          "platform": "windows,linux",
          "shortcut": "Ctrl+P",
          "keybindSets": ["devToolsDefault", "vsCode"]
        },
        {
          "platform": "windows,linux",
          "shortcut": "Ctrl+O",
          "keybindSets": ["devToolsDefault", "vsCode"]
        }
      ]
    },
    {
      "type": "context-menu-item",
      "location": "mainMenu/default",
      "actionId": "quickOpen.show"
    }
  ],
  "dependencies": [
    "ui",
    "diff"
  ],
  "scripts": [],
  "modules": [
    "quick_open.js",
    "quick_open-legacy.js",
    "FilteredListWidget.js",
    "QuickOpen.js",
    "CommandMenu.js",
    "HelpQuickOpen.js"
  ],
  "resources": [
    "filteredListWidget.css"
  ]
}

=== binaryage/dirac/resources/unpacked/devtools/front_end/console_counters/module.json
{
  "extensions": [
    {
      "type": "@UI.ToolbarItem.Provider",
      "className": "ConsoleCounters.WarningErrorCounter",
      "order": 1,
      "location": "main-toolbar-right"
    }
  ],
  "dependencies": [
    "common",
    "ui",
    "sdk"
  ],
  "scripts": [
    "WarningErrorCounter.js"
  ],
  "resources": [
    "errorWarningCounter.css"
  ]
}

=== binaryage/dirac/resources/unpacked/devtools/front_end/audits2/module.json
{
    "extensions": [
        {
            "type": "view",
            "location": "panel",
            "id": "audits2",
            "title": "Audits",
            "order": 90,
            "className": "Audits2.Audits2Panel"
        }
    ],
    "dependencies": [
        "components",
        "emulation",
        "timeline",
        "inspector_main",
        "sdk",
        "services",
        "ui"
    ],
    "scripts": [
        "lighthouse/renderer/util.js",
        "lighthouse/renderer/dom.js",
        "lighthouse/renderer/category-renderer.js",
        "lighthouse/renderer/details-renderer.js",
        "lighthouse/renderer/crc-details-renderer.js",
        "lighthouse/renderer/report-renderer.js",
        "Audits2Panel.js",
        "Audits2Dialog.js",
        "Audits2StatusView.js",
        "Audits2ProtocolService.js"
    ],
    "resources": [
        "audits2Dialog.css",
        "audits2Panel.css",
        "lighthouse/report-styles.css",
        "lighthouse/templates.html"
    ]
}

=== binaryage/dirac/resources/unpacked/devtools/front_end/worker_main/module.json
{
    "extensions": [
        {
            "type": "early-initialization",
            "className": "WorkerMain.WorkerMain"
        }
    ],
    "dependencies": [
        "components",
        "mobile_throttling"
    ],
    "scripts": [],
    "modules": [
        "worker_main.js",
        "WorkerMain.js"
    ]
}

=== binaryage/dirac/front_end/cm_web_modes/module.json
{
  "dependencies": [],
  "scripts": [],
  "modules": [
    "cm_web_modes.js",
    "cm_web_modes_cm.js",
    "cm_web_modes_headless.js",
    "css.js",
    "javascript.js",
    "xml.js",
    "htmlmixed.js",
    "htmlembedded.js",
    "wast.js"
  ],
  "skip_compilation": [
    "css.js",
    "javascript.js",
    "xml.js",
    "htmlmixed.js",
    "htmlembedded.js",
    "wast.js"
  ]
}

=== binaryage/dirac/front_end/event_listeners/module.json
{
    "dependencies": [
        "ui",
        "common",
        "components",
        "sdk",
        "object_ui"
    ],
    "scripts": [],
    "modules": [
        "event_listeners.js",
        "EventListenersView.js",
        "EventListenersUtils.js"
    ],
    "resources": [
        "eventListenersView.css"
    ]
}
