=== binaryage/dirac/scripts/json_validator/module.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "extensions": {
      "type": "array",
      "description": "Extension points",
      "items": {
        "properties": {
          "type": {"type": "string"},
          "order": {"type": "number"}
        }
      }
    },
    "dependencies": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "scripts": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "modules": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "resources": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "skip_compilation": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "experiment": {
      "type": "string"
    }
  },
  "definitions": {
  }
}

=== binaryage/dirac/front_end/resources/module.json
{
    "extensions": [
        {
            "type": "view",
            "location": "panel",
            "id": "resources",
            "title": "Application",
            "order": 70,
            "className": "Resources.ResourcesPanel",
            "tags": "pwa"
        },
        {
            "type": "@Common.Revealer",
            "contextTypes": [
                "SDK.Resource"
            ],
            "destination": "Application panel",
            "className": "Resources.ResourcesPanel.ResourceRevealer"
        }
    ],
    "dependencies": [
        "source_frame",
        "cookie_table",
        "inline_editor",
        "data_grid",
        "components",
        "object_ui",
        "perf_ui",
        "mobile_throttling",
        "network",
        "sources"
    ],
    "scripts": [
        "ApplicationCacheModel.js",
        "AppManifestView.js",
        "ApplicationCacheItemsView.js",
        "BackgroundServiceModel.js",
        "BackgroundServiceView.js",
        "ClearStorageView.js",
        "StorageItemsView.js",
        "CookieItemsView.js",
        "DatabaseModel.js",
        "DOMStorageModel.js",
        "DOMStorageItemsView.js",
        "DatabaseQueryView.js",
        "DatabaseTableView.js",
        "IndexedDBModel.js",
        "IndexedDBViews.js",
        "ResourcesPanel.js",
        "ApplicationPanelSidebar.js",
        "ResourcesSection.js",
        "ServiceWorkerCacheViews.js",
        "ServiceWorkersView.js"
    ],
    "resources": [
        "appManifestView.css",
        "backgroundServiceView.css",
        "clearStorageView.css",
        "indexedDBViews.css",
        "resourcesPanel.css",
        "resourcesSidebar.css",
        "serviceWorkerCacheViews.css",
        "serviceWorkersView.css"
    ]
}

=== binaryage/dirac/resources/unpacked/devtools/front_end/css_overview/module.json
{
    "extensions": [
        {
            "type": "view",
            "location": "panel",
            "id": "cssoverview",
            "title": "CSS Overview",
            "className": "CssOverview.CSSOverviewPanel",
            "order": 95,
            "experiment": "cssOverview"
        }
    ],
    "dependencies": [
        "elements",
        "ui",
        "sdk",
        "data_grid",
        "extensions"
    ],
    "modules": [
        "CSSOverviewController.js",
        "CSSOverviewUnusedDeclarations.js",
        "CSSOverviewModel.js",
        "CSSOverviewStartView.js",
        "CSSOverviewProcessingView.js",
        "CSSOverviewCompletedView.js",
        "CSSOverviewSidebarPanel.js",
        "CSSOverviewPanel.js"
    ],
    "scripts": [],
    "resources": [
        "cssOverview.css",
        "cssOverviewStartView.css",
        "cssOverviewProcessingView.css",
        "cssOverviewCompletedView.css",
        "cssOverviewSidebarPanel.css"
    ]
  }

=== binaryage/dirac/front_end/formatter_worker/module.json
{
    "dependencies": [
        "platform",
        "text_utils",
        "cm_headless"
    ],
    "scripts": [],
    "modules": [
        "formatter_worker.js",
        "../cm_web_modes/css.js",
        "../cm_web_modes/xml.js",
        "ESTreeWalker.js",
        "FormatterWorker.js",
        "acorn/acorn.js",
        "acorn/acorn_loose.js",
        "CSSFormatter.js",
        "AcornTokenizer.js",
        "JavaScriptFormatter.js",
        "FormattedContentBuilder.js",
        "CSSRuleParser.js",
        "HTMLFormatter.js",
        "IdentityFormatter.js",
        "JavaScriptOutline.js",
        "RelaxedJSONParser.js"
    ],
    "skip_compilation": [
        "acorn/acorn.js",
        "acorn/acorn_loose.js",
        "../cm_web_modes/css.js",
        "../cm_web_modes/xml.js"
    ]
}

=== binaryage/dirac/front_end/source_frame/module.json
{
  "extensions": [
    {
      "type": "setting",
      "category": "Sources",
      "title": "Default indentation:",
      "settingName": "textEditorIndent",
      "settingType": "enum",
      "defaultValue": "    ",
      "options": [
        {
          "title": "Set indentation to 2 spaces",
          "text": "2 spaces",
          "value": "  "
        },
        {
          "title": "Set indentation to 4 spaces",
          "text": "4 spaces",
          "value": "    "
        },
        {
          "title": "Set indentation to 8 spaces",
          "text": "8 spaces",
          "value": "        "
        },
        {
          "title": "Set indentation to tab character",
          "text": "Tab character",
          "value": "\t"
        }
      ]
    }
  ],
  "dependencies": [
    "text_editor",
    "ui",
    "platform",
    "persistence",
    "formatter",
    "object_ui",
    "workspace_diff"
  ],
  "scripts": [],
  "modules": [
    "source_frame.js",
    "source_frame-legacy.js",
    "BinaryResourceViewFactory.js",
    "SourcesTextEditor.js",
    "FontView.js",
    "ImageView.js",
    "SourceFrame.js",
    "ResourceSourceFrame.js",
    "JSONView.js",
    "XMLView.js",
    "PreviewFactory.js",
    "SourceCodeDiff.js"
  ],
  "resources": [
    "fontView.css",
    "imageView.css",
    "jsonView.css",
    "messagesPopover.css",
    "xmlTree.css",
    "xmlView.css",
    "resourceSourceFrame.css"
  ]
}

=== binaryage/dirac/resources/unpacked/devtools/front_end/audits2_worker/module.json
{
    "dependencies": [
        "worker_service"
    ],
    "extensions": [
        {
            "type": "@Service",
            "factoryName": "Audits2Service",
            "name": "Audits2Service"
        }
    ],
    "scripts": [
        "lighthouse/lighthouse-dt-bundle.js",
        "Audits2Service.js"
    ],
    "skip_compilation": [
        "lighthouse/lighthouse-dt-bundle.js"
    ]
}

=== binaryage/dirac/resources/unpacked/devtools/front_end/terminal/module.json
{
    "extensions": [
        {
            "type": "view",
            "location": "drawer-sidebar",
            "id": "drawer.xterm",
            "title": "Terminal",
            "order": 10,
            "factoryName": "Terminal.TerminalWidget"
        }
    ],
    "dependencies": [
        "components",
        "ui",
        "services"
    ],
    "experiment": "terminalInDrawer",
    "scripts": [
        "xterm.js/build/xterm.js",
        "xterm.js/addons/fit/fit.js",
        "TerminalWidget.js"
    ],
    "skip_compilation": [
        "xterm.js/build/xterm.js",
        "xterm.js/addons/fit/fit.js"
    ],
    "resources": [
        "terminal.css",
        "xterm.js/build/xterm.css"
    ]
}

=== binaryage/dirac/resources/unpacked/devtools/front_end/accessibility/module.json
{
    "extensions": [
        {
            "type": "view",
            "location": "elements-sidebar",
            "id": "accessibility.view",
            "title": "Accessibility",
            "order": 10,
            "persistence": "permanent",
            "className": "Accessibility.AccessibilitySidebarView"
        }
    ],
    "dependencies": ["elements"],
    "scripts": [],
    "modules": [
        "accessibility.js",
        "accessibility-legacy.js",
        "AccessibilityModel.js",
        "AccessibilitySidebarView.js",
        "AccessibilityNodeView.js",
        "AccessibilityStrings.js",
        "AccessibilitySubPane.js",
        "ARIAProperties.js",
        "ARIAAttributesView.js",
        "ARIAMetadata.js",
        "AXBreadcrumbsPane.js"
    ],
    "skip_compilation": [
        "ARIAProperties.js"
    ],
    "resources": [
        "accessibilityNode.css",
        "accessibilityProperties.css",
        "axBreadcrumbs.css"
    ]
}

=== binaryage/dirac/front_end/webauthn/module.json
{
  "extensions": [
    {
      "type": "view",
      "location": "drawer-view",
      "id": "webauthn-pane",
      "title": "WebAuthn",
      "order": 100,
      "persistence": "closeable",
      "className": "Webauthn.WebauthnPane",
      "experiment": "webauthnPane"
    }
  ],
  "dependencies": [
    "common",
    "platform",
    "ui",
    "host"
  ],
  "scripts": [],
  "modules": [
    "webauthn.js",
    "WebauthnPane.js",
    "webauthn-legacy.js"
  ],
  "resources": [
    "webauthnPane.css"
  ]
}
